#!/bin/zsh
todaysgreeting=`shuf -n 1 ~/purgatory/text/greetings`
while :
do
	output="$todaysgreeting | $(date '+%a %b %d %Y %I:%M %p')"

	battery="${${$(upower --dump | grep percentage | head -n 1)//\ }//percentage:}"
	state="${${$(upower --dump | grep state | head -n 1)//\ }//state:}"
	if [ "$state" = "charging" ]; then
		battery="$battery C"
	fi
	if [ -n "$battery" ]; then
		output="$output | $battery"
	fi

	xsetroot -name "$output"
	sleep 1
done
