#!/bin/zsh
todaysgreeting=`shuf -n 1 ~/purgatory/text/greetings`
while :
do
	touch ~/purgatory/text/remind

	a="$(date +%s)"
	for i in $( ls ~/purgatory/text/reminders ); do
		now="$(date +%s)"
		time="$(date -d "$(cat ~/purgatory/text/reminders/$i)" +%s)"
		if [ $now -ge $time ]; then
			echo -n $i " " >> ~/purgatory/text/remind
			rm ~/purgatory/text/reminders/$i
		fi
	done
	
	remind="$(cat ~/purgatory/text/remind)"

	output="$todaysgreeting | $(date '+%a, %b %d, %Y, %I:%M %p')"
	if [ -n "$remind" ]; then
		output=">> $remind << | $output"
	fi
	xsetroot -name "$output"
	sleep 1
done
